### ISSUE TITLE
Invalid config for [maxhomeautomation]:

### ISSUE THREAD

**Issue by banolka** [koleo9am/hass_max_home_automation#3]
Hi, I'm trying to setup this ( I have this docker to run the MAX! home app on my UNRAID server - https://github.com/rhopman/max-home-automation)

I get this error

```
Invalid config for [maxhomeautomation]: [cube_hex_address] is an invalid option for [maxhomeautomation]. Check: maxhomeautomation->maxhomeautomation->gateways->0->cubes->0->cube_hex_address. (See /config/configuration.yaml, line 172). Please check the docs at https://home-assistant.io/components/maxhomeautomation/
Connection lost. Reconnecting…
```

here is my config

```
#################################################################
## hass_max_home_automation
## https://github.com/koleo9am/hass_max_home_automation
#################################################################

maxhomeautomation:
  gateways:
    host: 192.168.1.236
    port: 1234
    scan_interval: 10
    cubes:
      - cube_hex_address: 17245A
        name: CUBE
        radiator_thermostats:
          - hex_address: 1A2DCB
            name: MAN CAVE
```

**Comment by koleo9am** [comment]
There should be only "hex_address" instead of "cube_hex_address".
Corrected in last commit.

**Comment by banolka** [comment]
Ok changed but now I get different error :/

```
homeassistant.components.hassio] Invalid config for [maxhomeautomation]: required key not provided @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['eco_buttons'][0]['hex_address']. Got None
required key not provided @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['eco_buttons'][0]['name']. Got None
required key not provided @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['wall_thermostats'][0]['hex_address']. Got None
required key not provided @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['wall_thermostats'][0]['name']. Got None
required key not provided @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['window_shutters'][0]['hex_address']. Got None
required key not provided @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['window_shutters'][0]['name']. Got None. 
```

**Comment by koleo9am** [comment]
Try this:

```yaml
maxhomeautomation:
  gateways:
    host: 192.168.1.236
    port: 1234
    scan_interval: 10
    cubes:
      - hex_address: 17245A
        name: CUBE
        radiator_thermostats:
          - hex_address: 1A2DCB
            name: "MAN CAVE"
        wall_thermostats:
        window_shutters:
        eco_buttons:      
```

**Comment by banolka** [comment]
Thanks for the support :) now with below config it is working :)

```
maxhomeautomation:
  gateways:
    host: 192.168.1.236
    port: 8080
    scan_interval: 10
    cubes:
      - hex_address: 17245A
        name: CUBE
        radiator_thermostats:
          - hex_address: 1A2DCB
            name: "MAN CAVE"
          - hex_address: 12039C
            name: "SALON"
          - hex_address: 1A38C8
            name: "GIRLS"
          - hex_address: 12O716
            name: "SYPILANIA"
        wall_thermostats:
        window_shutters:
        eco_buttons: 
```
