### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by HeimdallMidgard** [koleo9am/hass_max_home_automation#6]
Hello,

Iam trying to get your awesome component to work. Most prob the best solution to get it working with HA. But I got a problem with the installation. I got my max home assistant running so far but without thermostats since they are still on the way... Unfort. I get this error when validating my config: 

> Invalid config for [maxhomeautomation]: string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['eco_buttons'][0]['hex_address']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['eco_buttons'][0]['name']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['name']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['radiator_thermostats'][0]['hex_address']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['radiator_thermostats'][0]['name']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['wall_thermostats'][0]['hex_address']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['wall_thermostats'][0]['name']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['window_shutters'][0]['hex_address']. Got None string value is None for dictionary value @ data['maxhomeautomation']['gateways'][0]['cubes'][0]['window_shutters'][0]['name']. Got None. (See /config/configuration.yaml, line 150). Please check the docs at https://home-assistant.io/components/maxhomeautomation/

I got HASS.IO Version 92.0 running on a Pi. Your files are located in /config/custom_components/maxhomeautomation/

Do I need to adjust sth? Did I forgot sth? Sorry Iam still new to HA and its my first custom component. Thanks :)

**Comment by koleo9am** [comment]
Hi,

  it looks like configuration problem. Can you share the conf "maxhomeautomation: .... ".

**Comment by koleo9am** [comment]
Acording to the error. There are missing some of the device lists.
I was not able to make the lists optional.

So, if you have no ie. eco button, you still have the "eco_buttons:" list in the conf, but with no items.

Example:
```yaml

maxhomeautomation:
  gateways:
    host: localhost
    port: 8080
    scan_interval: 10
    cubes:
      - hex_address: FFFFFF
        name: My CUBE
        radiator_thermostats:
          - hex_address: FFFFFF
            name: Some radiator
        wall_thermostats:
        window_shutters:
        eco_buttons:
```
